made OpenFeature implement EvaluationLifeCycle
open-feature/node-sdk pull request #44
Opened 2022-07-01 13:16 UTC by anudeepreddy

Signed-off-by: Anudeep Reddy <anudeepc85@gmail.com>

Hello👋,

I have worked on #13, the following are the changes that are included in the PR:
- Made the OpenFeature class implement EvaluationLifeCycle.
- made the getInstance static method public.
- changes the remaining static methods to non-static.

I would appreciate any feedback.

2022-07-05 15:19 UTC, toddbaert requested changes
Great work so far! Please just export a singleton instead of the class though.

2022-07-05 15:19 UTC, toddbaert commented on src/client.ts
> +  private openFeature: OpenFeature;
```suggestion

  private openFeature: OpenFeature;
```

2022-07-05 15:19 UTC, toddbaert commented on src/open-feature.ts
> +export class OpenFeature implements EvaluationLifeCycle {
Don't export this class at all, instead, just add something like this at the bottom of the file:

```
export const openFeature = OpenFeature.getInstance();
```

This way, we are EXPORTING an instance, and nobody should (nobody will be able) to call `OpenFeature.getInstance`.

Then, consuming code will just do:

`import { openFeature } from './open-feature.js'`, which will already be a singleton!

2022-07-05 15:21 UTC, toddbaert commented
@weyert This change will be breaking only in that it exports a lower case `openFeature` (an instance) instead of `OpenFeature` (a class). This is mostly a style choice, but I think it's the correct one and now is the time to do it. You should only have to change the case, nothing else should break.

2022-07-05 19:08 UTC, weyert commented
Why not rename the class to something different so that it doesn’t conflict with `OpenFeature`? To me, capitalised name indicates most often it’s a global/singleton instance

2022-07-05 20:21 UTC, toddbaert commented
> Why not rename the class to something different so that it doesn’t conflict with `OpenFeature`? To me, capitalised name indicates most often it’s a global/singleton instance

We no longer export the `OpenFeature` class, we just export this instance, which is better I think. It was supposed to be used as a singleton, so just exporting one is better.

I don't really mind if we export `OpenFeature` vs `openFeature`. I've seen both in singletons, TBH.

2022-07-06 07:35 UTC, anudeepreddy commented
> I don't really mind if we export OpenFeature vs openFeature. I've seen both in singletons, TBH.

What should be the name of the class if we export the singleton as OpenFeature? In case if Java and python it is named OpenFeatureAPI, should the same be done here aswell?

2022-07-06 14:12 UTC, toddbaert commented
> What should be the name of the class if we export the singleton as OpenFeature? In case if Java and python it is named OpenFeatureAPI, should the same be done here as well?

Yep, I think that's fine.

2022-07-06 15:03 UTC, toddbaert approved these changes
LGTM. @weyert I think this new version will have zero breaking changes.

2022-07-06 15:18 UTC, merged

2022-07-06 15:46 UTC, anudeepreddy commented
Looking forward to making more contributions 😄

2022-07-06 17:12 UTC, beeme1mr commented
Thanks @anudeepreddy!